# Generated by Django 3.2 on 2022-01-02 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(null=True)),
                ('question_image', models.TextField(null=True)),
                ('option_a', models.TextField(null=True)),
                ('option_a_image', models.TextField(null=True)),
                ('option_b', models.TextField(null=True)),
                ('option_b_image', models.TextField(null=True)),
                ('option_c', models.TextField(null=True)),
                ('option_c_image', models.TextField(null=True)),
                ('option_d', models.TextField(null=True)),
                ('option_d_image', models.TextField(null=True)),
                ('marks', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('registration', models.CharField(max_length=100, null=True)),
                ('tabs_switch', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.usertable')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section_dropdown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.section'),
        ),
    ]
