# Generated by Django 3.2 on 2022-01-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_when_not_started', models.TextField(null=True)),
                ('instruction_for_exam', models.TextField(null=True)),
                ('inst_when_time_out_during_exam', models.TextField(null=True)),
                ('Instruction_when_Logging_in_after_time_out', models.TextField(null=True)),
                ('msg_when_submit', models.TextField(null=True)),
                ('exam_start_time', models.DateTimeField(auto_now_add=True)),
                ('exam_end_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
