# Generated by Django 3.2 on 2022-01-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_usertable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting_table',
            name='Instruction_when_Logging_in_after_time_out',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting_table',
            name='exam_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='setting_table',
            name='exam_start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='setting_table',
            name='inst_when_time_out_during_exam',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting_table',
            name='instruction_for_exam',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting_table',
            name='msg_when_not_started',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting_table',
            name='msg_when_submit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
