# Generated by Django 3.2 on 2022-01-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20220102_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='tabs_switch',
            field=models.PositiveBigIntegerField(default=0, max_length=100, null=True),
        ),
    ]
