# Generated by Django 3.2 on 2022-01-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_setting_table_allow_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('staff', 'staff')], max_length=100, null=True),
        ),
    ]
