# Generated by Django 3.2 on 2022-01-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20220104_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting_table',
            name='add_question_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='setting_table',
            name='add_student_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
